"""empty message

Revision ID: dbaecad225d7
Revises: 1c3d24591df5
Create Date: 2019-02-12 21:49:05.557311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaecad225d7'
down_revision = '1c3d24591df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_bots')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('slack_bots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bot_access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='slack_bots_pkey')
    )
    # ### end Alembic commands ###
